### ISSUE TITLE
CoffeeScript error

### ISSUE THREAD

**Issue by sungwoncho** [agate/node-diff-parser#1]
I just installed node-diff-parser with `npm install diff-parser -g`.

When I run `diff2html` on the command line, I get this error:

```
/usr/local/lib/node_modules/diff-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:213
          throw new Error("Use CoffeeScript.register() or require the coffee-s
                ^
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object.base.(anonymous function) [as .coffee] (/usr/local/lib/node_modules/diff-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:213:17)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/diff-parser/bin/diff2html:7:14)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

When I try `diff2html myFilename.diff > myFilename.html`, I get the same.

I am using OSX and coffee-script@1.9.3 is installed globally using npm.

**Comment by cancerberoSgx** [comment]
same here. node 4.4.3. osx.
